### ISSUE TITLE
Webpack build error for 0.1.5

### ISSUE THREAD

**Issue by adamtal3** [miadwang/sou-react-table#10]
I've installed the latest version from npm (0.1.5) and got the following errors when building with Webpack:

`ERROR in ./~/sou-react-table/dist/SouTable.js
Module not found: Error: Can't resolve '/Users/Ding/Documents/projects/sou-react-table/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/classCallCheck'`

`ERROR in ./~/sou-react-table/dist/SouTable.js
Module not found: Error: Can't resolve '/Users/Ding/Documents/projects/sou-react-table/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/createClass'`

`ERROR in ./~/sou-react-table/dist/SouTable.js
Module not found: Error: Can't resolve '/Users/Ding/Documents/projects/sou-react-table/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn'`

`ERROR in ./~/sou-react-table/dist/SouTable.js
Module not found: Error: Can't resolve '/Users/Ding/Documents/projects/sou-react-table/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/getPrototypeOf'`

`ERROR in ./~/sou-react-table/dist/SouTable.js
Module not found: Error: Can't resolve '/Users/Ding/Documents/projects/sou-react-table/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/inherits'`

`ERROR in ./~/sou-react-table/dist/SouTable.js
Module not found: Error: Can't resolve '/Users/Ding/Documents/projects/sou-react-table/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/assertThisInitialized'`

**Comment by miadwang** [comment]
Fixed in 0.1.6
