### ISSUE TITLE
read-noly attribute

### ISSUE THREAD

**Issue by gooddaddy** [miadwang/sou-react-table#2]
i hope you can add read-noly attribute for cell

**Comment by miadwang** [comment]
Good idea! Thanks~
It's been so long since last version. I'm going to continue working on this project now.

**Comment by fff280840** [comment]
很需要这个功能啊，表头禁用编辑，大神赶紧更新

**Comment by miadwang** [comment]
@gooddaddy @fff280840 I looked into this issue today.
At first glance, a read-only cell is just a cell disabled from direct editing. On second thought, you may find that there is much to consider. Is it allowed to insert a cell in a read-only row or between two read-only cells? Which data structure is the best way to initialize a table with the read-only states? Should the states be saved? What will happen if a read-only cell is copied to another place? I can't answer those questions. And I found that there is no such feature in Apple Numbers and Google Sheets. sou-react-table is a lite sheet editor. Currently, I don't think it needs features that even powerful sheet editors don't.
Sorry that I will close this issue. Thanks for your suggestions.
