### ISSUE TITLE
The default setting crashes ... cannot populate tableData so it renders

### ISSUE THREAD

**Issue by ericlau-solid** [miadwang/sou-react-table#4]
This component has promise, but I cannot get it working at all even when I copy directly from demo:

```
tableData={[
                { 'City', 'Beijing', 'Shanghai', 'Guangzhou' },
                { 'Temperature', '5', '22', '29' },
                { 'Weather', 'Windy', 'Sunny', 'Rainy' },
              ]}
```

That is not valid array of arrays, and even if I put empty array, propTypes still complain and won't render.

**Comment by miadwang** [comment]
So sorry about my typo. It should be
`tableData={[
    [ 'City', 'Beijing', 'Shanghai', 'Guangzhou' ],
    [ 'Temperature', '5', '22', '29' ],
    [ 'Weather', 'Windy', 'Sunny', 'Rainy' ],
]}`

I will look at the empty array propTypes problem.

**Comment by miadwang** [comment]
Fixed in the latest version.
