### ISSUE TITLE
Is is possible to add collapsible rows? 

### ISSUE THREAD

**Issue by nimesha95** [miadwang/sou-react-table#9]
This is a feature request, 
Is it possible to add collapsible rows?

**Comment by miadwang** [comment]
![c](https://user-images.githubusercontent.com/19298162/46056746-be754380-c184-11e8-9494-5138c11fd51e.png)
You mean collapsible rows like this?

**Comment by nimesha95** [comment]
Yes, is it possible to do? :D

**Comment by nimesha95** [comment]
Edit: what i'm looking for is something like this.
[https://docs.handsontable.com/pro/5.0.2/demo-nested-rows.html](url)

**Comment by miadwang** [comment]
Sorry, I feel that nested rows are too edgy for a simple editable table component like sou-react-table.
And I don't see nested rows in the latest 6.0.0 version of Handsontable. Where does it go?
